import type { Metadata } from "next";
import { Afacad_Flux } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/styles.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const afacadFlux = Afacad_Flux({
  variable: "--font-afacad-flux",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
      <html lang="en" className={`${afacadFlux.variable}`}>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
  );
}
